/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.serviciosapi.HTTP;

import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class InterfazHTTP extends javax.swing.JFrame {

    /**
     * Creates new form InterfazHTTP
     */
    public InterfazHTTP() {
        initComponents();
        
        TextoOriginal.setLineWrap(true);
        TextoOriginal.setWrapStyleWord(true);
        TextoTraducido.setLineWrap(true);
        TextoTraducido.setWrapStyleWord(true);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TextoTraducido.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Salir = new javax.swing.JButton();
        Traducir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoOriginal = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextoTraducido = new javax.swing.JTextArea();
        Limpiar = new javax.swing.JButton();
        IdiomaO = new javax.swing.JComboBox<>();
        IdiomaD = new javax.swing.JComboBox<>();
        IdiomaOText = new javax.swing.JLabel();
        IdiomaDText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        Salir.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Salir.setText("Salir");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(519, 519, 519)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(Salir)
                .addGap(51, 51, 51))
        );

        Traducir.setBackground(new java.awt.Color(204, 204, 255));
        Traducir.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Traducir.setText("Traducir");
        Traducir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TraducirMouseClicked(evt);
            }
        });

        TextoOriginal.setBackground(new java.awt.Color(204, 204, 255));
        TextoOriginal.setColumns(20);
        TextoOriginal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TextoOriginal.setRows(5);
        jScrollPane1.setViewportView(TextoOriginal);

        TextoTraducido.setBackground(new java.awt.Color(204, 204, 255));
        TextoTraducido.setColumns(20);
        TextoTraducido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TextoTraducido.setRows(5);
        jScrollPane2.setViewportView(TextoTraducido);

        Limpiar.setBackground(new java.awt.Color(204, 204, 255));
        Limpiar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Limpiar.setText("Limpiar");
        Limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LimpiarMouseClicked(evt);
            }
        });
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        IdiomaO.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        IdiomaO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Inglés", "Francés", "Alemán", "Italiano", "Portugués" }));

        IdiomaD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        IdiomaD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Inglés", "Francés", "Alemán", "Italiano", "Portugués" }));
        IdiomaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdiomaDActionPerformed(evt);
            }
        });

        IdiomaOText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        IdiomaOText.setText("Idioma de Origen:");

        IdiomaDText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        IdiomaDText.setText("Idioma de Destino:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(Limpiar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(IdiomaOText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IdiomaO, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(IdiomaDText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(IdiomaD, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(Traducir, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(Limpiar)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdiomaOText)
                    .addComponent(IdiomaO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdiomaD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdiomaDText))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(29, 29, 29)
                .addComponent(Traducir)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TraducirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TraducirMouseClicked
        
        // Obtener el texto ingresado
    String texto = TextoOriginal.getText();

    // Obtener los idiomas seleccionados
    String idiomaOrigen = IdiomaO.getSelectedItem().toString();
    String idiomaDestino = IdiomaD.getSelectedItem().toString();

    // Validar que no estén vacíos y que sean diferentes
    if (texto.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese un texto para traducir.", "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (idiomaOrigen.equals(idiomaDestino)) {
        JOptionPane.showMessageDialog(this, "Seleccione diferentes idiomas para traducir.", "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Obtener los códigos de idioma
    String codigoOrigen = Language.getLanguages().get(idiomaOrigen);
    String codigoDestino = Language.getLanguages().get(idiomaDestino);

    // Llamar al servicio de traducción
    String traduccion = TranslatorService.translate(texto, codigoOrigen, codigoDestino);

    // Mostrar la traducción en la caja de texto
    TextoTraducido.setText(traduccion);
    TextoTraducido.setEditable(false); // Evitar edición del resultado
    }//GEN-LAST:event_TraducirMouseClicked

    private void LimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LimpiarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LimpiarMouseClicked

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        
        // Restablecer JComboBox al primer elemento
    IdiomaO.setSelectedIndex(0);
    IdiomaD.setSelectedIndex(0);

    // Limpiar JTextArea
    TextoOriginal.setText("");
    TextoTraducido.setText("");

    // Bloquear el JTextArea de traducción para evitar que el usuario escriba en él
    TextoTraducido.setEditable(false);
    }//GEN-LAST:event_LimpiarActionPerformed

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
       
         System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void IdiomaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdiomaDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdiomaDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazHTTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazHTTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazHTTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazHTTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazHTTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> IdiomaD;
    private javax.swing.JLabel IdiomaDText;
    private javax.swing.JComboBox<String> IdiomaO;
    private javax.swing.JLabel IdiomaOText;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Salir;
    private javax.swing.JTextArea TextoOriginal;
    private javax.swing.JTextArea TextoTraducido;
    private javax.swing.JButton Traducir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
